### ISSUE TITLE
Add a way to display version number

### ISSUE THREAD

**Issue by tokyojimu** [paulrosania/tron#2]
Would be helpful if we could do something like
tron --version
to get the version number of the binary we are currently running, for comparison with the latest release.

**Comment by tessro** [comment]
Yes, this is a very good idea. We should be able to do this via a constant fed in from CI. I will add it to my todo list.

**Comment by tessro** [comment]
Added `tron version` in https://github.com/paulrosania/tron/releases/tag/v1.0.4
